### ISSUE TITLE
Avoid using ruby version restriction in the gem spec file

### ISSUE THREAD

**Issue by anatol** [bkuhlmann/milestoner#1]
The gemspec contains ruby version restriction  `spec.required_ruby_version = "~> 2.7"`. Avoid doing it as this library might be used by other tools that have different version requirements.

For example I am trying to use a project that depends on `milestones ~> 10.0` and it cannot be used with ruby 3 due to unnecessarly strict requirement in this spec file.

**Comment by bkuhlmann** [comment]
Hey Anatol. :wave: Thanks for the suggestion. Actually, I'm way ahead of you. :wink: Ruby 3.0.0 support was added as early as Version 11.0.0. See the [changes](https://www.alchemists.io/projects/milestoner/changes.html) for details.

If you upgrade to 11.2.0, you'll have all you need. :tada:

By the way, the version check is super important since I don't want to break older versions that only support Ruby 2.7.2 or older. This is why Milestoner had a major version bump from 10.0.0 to 11.0.0 since the 10.0.0 version line only supports Ruby 2.7.0 while 11.0.0 supports Ruby 3.0.0.

**Comment by anatol** [comment]
The problem that software is third-party and I have no interest to modify/rebuild it. The software would work fine except rubygems does not allow to load `milestoner ~> 10` at ruby3.

The 11.2 did **not** remove the ruby version restriction, it just bumped it. Such restriction is harmful and it creates unneeded problems to users.
